version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    volumes:
      - ./node/app:/usr/src/app
      - /usr/src/app/node_modules #volume anonimo para não dar erro na hora do npm install
    ports:
      - "3000:3000"
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:8080"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge